#ifndef __GOLDILOCKS_CONFIG_H__
#define __GOLDILOCKS_CONFIG_H__ 1

#define GOLDILOCKS_USE_PTHREAD 1
#define EXPERIMENT_ECDH_OBLITERATE_CT 0
#define EXPERIMENT_ECDH_STIR_IN_PUBKEYS 0
#define GOLDILOCKS_SHAKE 256

#endif  // __GOLDILOCKS_CONFIG_H__
