#ifndef __GOLDILOCKS_CONFIG_H__
#define __GOLDILOCKS_CONFIG_H__ 1

#define GOLDILOCKS_USE_PTHREAD 1
#define EXPERIMENT_ECDH_OBLITERATE_CT 1
#define EXPERIMENT_ECDH_STIR_IN_PUBKEYS 1

#endif  // __GOLDILOCKS_CONFIG_H__
